[settings]
experimental = true
python_compile = false

[tools]
"go:github.com/charmbracelet/glow" = "latest"
"cargo:git-delta" = "latest"
go = "latest"
node = "22"
"npm:pnpm" = "latest"
fx = "latest"
"cargo:bandwhich" = "latest"
"cargo:mprocs" = "latest"
"cargo:rainfrog" = "latest"
deno = "latest"
"cargo:bat" = "latest"
uv = "latest"
"cargo:exa" = "latest"
pipx = "latest"
"cargo:du-dust" = "latest"
"cargo:ripgrep" = "latest"
fzf = "latest"
"cargo:yazi-fm" = "latest"
"cargo:yazi-cli" = "latest"
kind = "latest"
jq = "latest"
"cargo:difftastic" = "latest"
"cargo:mcfly" = "latest"
"cargo:https://github.com/bnprks/mcfly-fzf" = "branch:main"
"cargo:gitu" = "latest"
"cargo:cargo-watch" = "latest"
"cargo:fd-find" = "latest"
usage = "latest"
python = "system"
rye = "latest"
"pipx:httpie" = "latest"
talhelper = "latest"
mc = "latest"
"cargo:viddy" = "latest"
gitu = "latest"
