[settings]
experimental = true

[tools]
"go:github.com/charmbracelet/glow" = "latest"
"cargo:git-delta" = "latest"
python = "3.12"
go = "latest"
node = "22"
"npm:pnpm" = "latest"
rye = "latest"
fx = "latest"
"cargo:bandwhich" = "latest"
ni = "latest"
"cargo:mprocs" = "latest"
gradle = "latest"
