[settings]
experimental = true

[tools]
"go:github.com/charmbracelet/glow" = "latest"
"cargo:git-delta" = "latest"
go = "latest"
node = "22"
"npm:pnpm" = "latest"
rye = "latest"
fx = "latest"
"cargo:bandwhich" = "latest"
"cargo:mprocs" = "latest"
"cargo:rainfrog" = "latest"
deno = "latest"
"cargo:bat" = "latest"
uv = "latest"
"cargo:exa" = "latest"
python = "3.12"
pipx = "latest"
gradle = "latest"
"cargo:du-dust" = "latest"
"cargo:ripgrep" = "latest"
fzf = "latest"
"cargo:yazi-fm" = "latest"
"cargo:yazi-cli" = "latest"
kind = "latest"
jq = "latest"
"cargo:difftastic" = "latest"
"cargo:mcfly" = "latest"
"cargo:https://github.com/bnprks/mcfly-fzf" = "branch:main"
"cargo:gitu" = "latest"
