format = """
$os\
$username\
$directory\
$git_branch\
$git_status\
$c\
$elixir\
$elm\
$golang\
$gradle\
$haskell\
$java\
$julia\
$nodejs\
$nim\
$rust\
$scala\
[\n](fg:#7C6F64)\
$character
"""

# Disable the blank line at the start of the prompt
# add_newline = false

# You can also replace your username with a neat symbol like   or disable this
# and use the os module below
[username]
show_always = true
style_user = "fg:green"
style_root = "fg:red"
format = '[$user ]($style)'
disabled = false

[character]
format = "$symbol"
success_symbol = '[🯁🯂🯃 ](bold green)'
error_symbol = '[🯁🯂🯃 ](bold red)'

[directory]
style = "fg:gray"
format = "[ $path ]($style)"
truncation_length = 10
truncation_symbol = "…/"
truncate_to_repo = true

[c]
symbol = " "
style = "fg:white"
format = '[ $symbol ($version) ]($style)'

[docker_context]
symbol = ""
style = "fg:white"
format = '[ $symbol $context ]($style)'

[elixir]
symbol = " "
style = "fg:white"
format = '[ $symbol ($version) ]($style)'

[elm]
symbol = " "
style = "fg:white"
format = '[ $symbol ($version) ]($style)'

[git_branch]
symbol = ""
style = "fg:white"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "fg:yellow"
modified = "  ×${count}"
ahead = " ⇑ ×${count}"
behind = " ⇓ ×${count}"
diverged = " ⇑ ×${ahead_count} ⇓ ×${behind_count}"
staged = "  ×${count}"
untracked = "  ×${count}"
stashed = ""
deleted = "  ×${count}"
format = '[$all_status$ahead_behind ]($style)'

[golang]
symbol = " "
style = "fg:white"
format = '[ $symbol ($version) ]($style)'

[gradle]
style = "fg:white"
format = '[ $symbol ($version) ]($style)'

[haskell]
symbol = " "
style = "fg:white"
format = '[ $symbol ($version) ]($style)'

[java]
symbol = " "
style = "fg:white"
format = '[ $symbol ($version) ]($style)'

[julia]
symbol = " "
style = "fg:white"
format = '[ $symbol ($version) ]($style)'

[nodejs]
symbol = ""
style = "fg:green"
format = '[ $symbol ($version) ]($style)'

[nim]
symbol = " "
style = "fg:white"
format = '[ $symbol ($version) ]($style)'

[rust]
symbol = ""
style = "fg:white"
format = '[ $symbol ($version) ]($style)'

[scala]
symbol = " "
style = "fg:white"
format = '[ $symbol ($version) ]($style)'

[time]
disabled = true
time_format = "%R" # Hour:Minute Format
style = "fg:white"
format = '[ ♥ $time ]($style)'
